# Generated by Django 4.2.6 on 2023-12-02 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAreaEvaluacion', models.CharField(max_length=60)),
                ('DescipcionAreaEvaluacion', models.CharField(max_length=250)),
                ('EstadoAreaEvaluacion', models.CharField(default='Disponible', max_length=60)),
                ('Porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCategoria', models.CharField(max_length=60)),
                ('DescipcionCategoria', models.CharField(max_length=250)),
                ('EstadoCategoria', models.CharField(default='Disponible', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompetencia', models.CharField(max_length=60)),
                ('DescipcionCompetencia', models.CharField(max_length=250)),
                ('LugarCompetencia', models.CharField(max_length=150)),
                ('FechaCompetencia', models.DateField(default=datetime.date.today)),
                ('FechaLimiteInscripcion', models.DateField(default=datetime.date.today)),
                ('FechaLimiteActualizarDatos', models.DateField(default=datetime.date.today)),
                ('EstadoCompetencia', models.CharField(default='Disponible', max_length=60)),
                ('banner1', models.CharField(max_length=250, null=True)),
                ('banner2', models.CharField(max_length=250, null=True)),
                ('banner3', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRobot', models.CharField(max_length=60)),
                ('DescripcionRobot', models.CharField(max_length=250)),
                ('imagen_robot', models.CharField(max_length=250, null=True)),
                ('diagrama_conexiones', models.CharField(max_length=250, null=True)),
                ('programacion_robot', models.CharField(max_length=250, null=True)),
                ('EstadoRobot', models.CharField(default='Activo', max_length=60)),
                ('FechaRegistro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRegla', models.CharField(max_length=60)),
                ('DescipcionRegla', models.CharField(max_length=250)),
                ('EstadoRegla', models.CharField(default='Disponible', max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Regla', to='competencia.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='inscripcion_competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_inscripcion', models.CharField(default='Registrado', max_length=60)),
                ('FechaInscripcion', models.DateField(default=datetime.date.today)),
                ('oportunidad1', models.IntegerField(null=True)),
                ('oportunidad2', models.IntegerField(null=True)),
                ('oportunidad3', models.IntegerField(null=True)),
                ('color', models.CharField(default='Sin color', max_length=60)),
                ('imagen_aplicacion', models.CharField(max_length=250, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_categoria', to='competencia.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_equipo', to='login.equipo')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_robot', to='competencia.robot')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='competencia.competencia'),
        ),
        migrations.CreateModel(
            name='asignacion_jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(default=datetime.date.today)),
                ('estado_asignacion', models.CharField(default='Activa', max_length=60)),
                ('area_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaEvaluacion', to='competencia.areaevaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='login.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='areaevaluacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaEvaluacion', to='competencia.categoria'),
        ),
    ]
