# Generated by Django 4.2.6 on 2023-12-02 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEquipoLogistica', models.CharField(max_length=60)),
                ('DescipcionEquipoLogistica', models.CharField(max_length=250)),
                ('EstadoEquipoLogistica', models.CharField(default='Disponible', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaParticipacion', models.DateField(default=datetime.date.today)),
                ('estado_participacion', models.CharField(default='Activa', max_length=60)),
                ('equipo_logistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipacionEquipoLogistica', to='competencia.equipologistica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioEquipoLogistica', to='login.usuario')),
            ],
        ),
    ]
