# Generated by Django 4.2.6 on 2023-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='')),
                ('banner2', models.ImageField(upload_to='')),
                ('banner3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='areaevaluacion',
            name='Porcentaje',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
