# Generated by Django 4.2.6 on 2023-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0003_equipologistica_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipologistica',
            name='DescipcionEquipoLogistica',
            field=models.CharField(max_length=450),
        ),
    ]
