# Generated by Django 4.2.6 on 2023-11-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_alter_prueba_banner1_alter_prueba_banner2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.AddField(
            model_name='competencia',
            name='banner1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='banner2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='banner3',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
