# Generated by Django 4.2.6 on 2023-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_alter_equipologistica_descipcionequipologistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion_competencia',
            name='resultado_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion_competencia',
            name='oportunidad1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion_competencia',
            name='oportunidad2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion_competencia',
            name='oportunidad3',
            field=models.FloatField(null=True),
        ),
    ]
