# Generated by Django 4.2.6 on 2023-12-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0005_inscripcion_competencia_resultado_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_EquipoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTarea', models.CharField(max_length=60)),
                ('DescipcionTarea', models.CharField(max_length=250)),
                ('EstadoTarea', models.CharField(default='Disponible', max_length=60)),
                ('equipo_logistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TareasEquipoLogistica', to='competencia.equipologistica')),
            ],
        ),
    ]
