# Generated by Django 4.2.6 on 2023-11-25 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuario_tipo_usuario'),
        ('competencia', '0006_areaevaluacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaevaluacion',
            name='usuario',
        ),
        migrations.CreateModel(
            name='asignacion_jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(default=datetime.date.today)),
                ('estado_asignacion', models.CharField(default='Activa', max_length=60)),
                ('area_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaEvaluacion', to='competencia.areaevaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='login.usuario')),
            ],
        ),
    ]
