# Generated by Django 4.2.6 on 2023-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0008_robot_inscripcion_competencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion_competencia',
            name='codigo_carro',
        ),
        migrations.RemoveField(
            model_name='inscripcion_competencia',
            name='diagrama_conexiones',
        ),
        migrations.RemoveField(
            model_name='inscripcion_competencia',
            name='imagen_robot',
        ),
        migrations.AddField(
            model_name='robot',
            name='diagrama_conexiones',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='imagen_robot',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='programacion_robot',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
