# Generated by Django 4.2.6 on 2023-12-02 14:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEquipo', models.CharField(max_length=60)),
                ('DescipcionEquipo', models.CharField(max_length=250)),
                ('imagen_equipo', models.CharField(max_length=250, null=True)),
                ('video_equipo', models.CharField(max_length=250, null=True)),
                ('EstadoEquipo', models.CharField(default='Activo', max_length=60)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipoUsuario', models.CharField(max_length=60)),
                ('DescipcionTipoUsuario', models.CharField(max_length=250)),
                ('EstadoTipoUsuario', models.CharField(default='Disponible', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre1', models.CharField(max_length=60)),
                ('Nombre2', models.CharField(blank=True, max_length=60)),
                ('Apellido1', models.CharField(max_length=60)),
                ('Apellido2', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('sexo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='login.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_ParticipanteEquipo', models.CharField(default='Activo', max_length=60)),
                ('fecha_ParticipanteEquipo', models.DateField(default=datetime.date.today)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantesEquipos', to='login.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantesUsuarios', to='login.usuario')),
            ],
        ),
    ]
