# Generated by Django 4.2.6 on 2023-10-22 20:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre1', models.CharField(max_length=60)),
                ('Nombre2', models.CharField(blank=True, max_length=60)),
                ('Apellido1', models.CharField(max_length=60)),
                ('Apellido2', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('sexo', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
