# Generated by Django 4.2.6 on 2023-10-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
