# Generated by Django 4.2.6 on 2023-12-01 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEquipo', models.CharField(max_length=60)),
                ('DescipcionEquipo', models.CharField(max_length=250)),
                ('imagen_equipo', models.CharField(max_length=250, null=True)),
                ('video_equipo', models.CharField(max_length=250, null=True)),
                ('EstadoEquipo', models.CharField(default='Activo', max_length=60)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipoUsuario', models.CharField(max_length=60)),
                ('DescipcionTipoUsuario', models.CharField(max_length=250)),
                ('EstadoTipoUsuario', models.CharField(default='Disponible', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_ParticipanteEquipo', models.CharField(default='Activo', max_length=60)),
                ('fecha_ParticipanteEquipo', models.DateField(default=datetime.date.today)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantesEquipos', to='login.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantesUsuarios', to='login.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='login.tipousuario'),
            preserve_default=False,
        ),
    ]
