# Generated by Django 4.2.6 on 2023-11-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipoUsuario', models.CharField(max_length=60)),
                ('DescipcionTipoUsuario', models.CharField(max_length=250)),
                ('EstadoTipoUsuario', models.CharField(default='Disponible', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='login.tipousuario'),
            preserve_default=False,
        ),
    ]
