# Generated by Django 4.2.6 on 2023-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_equipo_participantesequipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_equipo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='video_equipo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
