# Generated by Django 4.2.6 on 2023-11-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencia', '0005_delete_prueba_competencia_banner1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.FloatField()),
                ('area_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CriterioEvaluacion', to='competencia.areaevaluacion')),
            ],
        ),
    ]
