# Generated by Django 4.2.6 on 2023-11-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterioevaluacion',
            old_name='nombre',
            new_name='nombre_Criterio',
        ),
        migrations.RenameField(
            model_name='criterioevaluacion',
            old_name='porcentaje',
            new_name='porcentaje_Criterio',
        ),
    ]
